<?php

// autoload_classmap.php @generated by Composer

$dependenciesDir = dirname(__DIR__);
$baseDir = dirname($dependenciesDir);

return array(
    'Composer\\InstalledVersions' => $dependenciesDir . '/composer/InstalledVersions.php',
);
