<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0126d801b599ca56ac357764b6359912
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'F' => 
        array (
            'Fraob\\FranflixWebapp\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Fraob\\FranflixWebapp\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PayPal' => 
            array (
                0 => __DIR__ . '/..' . '/paypal/rest-api-sdk-php/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0126d801b599ca56ac357764b6359912::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0126d801b599ca56ac357764b6359912::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit0126d801b599ca56ac357764b6359912::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit0126d801b599ca56ac357764b6359912::$classMap;

        }, null, ClassLoader::class);
    }
}
