<?php

// autoload_namespaces.php @generated by Composer

$dependenciesDir = dirname(__DIR__);
$baseDir = dirname($dependenciesDir);

return array(
    'PayPal' => array($dependenciesDir . '/paypal/rest-api-sdk-php/lib'),
);
