<?php

// autoload_psr4.php @generated by Composer

$dependenciesDir = dirname(__DIR__);
$baseDir = dirname($dependenciesDir);

return array(
    'Stripe\\' => array($dependenciesDir . '/stripe/stripe-php/lib'),
    'Psr\\Log\\' => array($dependenciesDir . '/psr/log/Psr/Log'),
    'Fraob\\FranflixWebapp\\' => array($baseDir . '/src'),
);
